from __future__ import annotations

Exercise = dict[str, object]

EXERCISES: list[Exercise] = [
    {
        "id": "Q001",
        "level": "Beginner",
        "topic": "Files",
        "question": "Which command shows the current directory?",
        "options": ["pwd", "ps", "df", "ss"],
        "answer": "pwd",
        "explanation": "pwd prints the current working directory.",
        "points": 5,
    },
    {
        "id": "Q002",
        "level": "Beginner",
        "topic": "Disk",
        "question": "Which command first checks filesystem capacity?",
        "options": ["df -h", "free -h", "grep -r", "ping"],
        "answer": "df -h",
        "explanation": "df reports filesystem capacity and usage.",
        "points": 5,
    },
    {
        "id": "Q003",
        "level": "Beginner",
        "topic": "Disk",
        "question": "After df shows /var is full, which command helps locate the large directory?",
        "options": ["du -xhd1 /var", "uptime", "dig example.com", "systemctl enable nginx"],
        "answer": "du -xhd1 /var",
        "explanation": "du estimates directory usage; -x stays on one filesystem and -d1 limits depth.",
        "points": 5,
    },
    {
        "id": "Q004",
        "level": "Beginner",
        "topic": "Memory",
        "question": "Which free column is most useful when assessing immediately usable memory?",
        "options": ["available", "shared", "total", "swap total"],
        "answer": "available",
        "explanation": "Available memory accounts for reclaimable cache and is more useful than the free column alone.",
        "points": 5,
    },
    {
        "id": "Q005",
        "level": "Beginner",
        "topic": "Logs",
        "question": "Which command displays the final 100 lines of a log?",
        "options": ["tail -n 100 file.log", "cat -n 100 file.log", "df -n 100", "ps -n 100"],
        "answer": "tail -n 100 file.log",
        "explanation": "tail -n controls the number of final lines displayed.",
        "points": 5,
    },
    {
        "id": "Q006",
        "level": "Beginner",
        "topic": "Logs",
        "question": "What does grep -i do?",
        "options": ["Ignores case", "Deletes matches", "Shows inode usage", "Follows a file"],
        "answer": "Ignores case",
        "explanation": "The -i flag performs case-insensitive matching.",
        "points": 5,
    },
    {
        "id": "Q007",
        "level": "Beginner",
        "topic": "Processes",
        "question": "Which command can sort processes by memory usage?",
        "options": ["ps aux --sort=-%mem", "df -i", "ip route", "tar -tf"],
        "answer": "ps aux --sort=-%mem",
        "explanation": "ps supports sorting by resource fields such as %mem.",
        "points": 5,
    },
    {
        "id": "Q008",
        "level": "Beginner",
        "topic": "Safety",
        "question": "Why is chmod 777 usually a poor fix?",
        "options": ["It grants excessive permissions", "It compresses the file", "It changes DNS", "It stops systemd"],
        "answer": "It grants excessive permissions",
        "explanation": "Mode 777 gives read, write, and execute permissions to everyone.",
        "points": 5,
    },
    {
        "id": "Q009",
        "level": "Intermediate",
        "topic": "Services",
        "question": "What should normally precede restarting a failed service?",
        "options": [
            "Inspect status and logs",
            "Delete its configuration",
            "Reboot immediately",
            "Disable the firewall",
        ],
        "answer": "Inspect status and logs",
        "explanation": "Status and logs preserve evidence and reduce unnecessary disruption.",
        "points": 10,
    },
    {
        "id": "Q010",
        "level": "Intermediate",
        "topic": "Services",
        "question": "Which command filters journal entries for nginx?",
        "options": ["journalctl -u nginx", "tail -u nginx", "ps -u nginx.conf", "df -u nginx"],
        "answer": "journalctl -u nginx",
        "explanation": "journalctl -u filters entries for a systemd unit.",
        "points": 10,
    },
    {
        "id": "Q011",
        "level": "Intermediate",
        "topic": "Network",
        "question": "Which command confirms that a process is listening on TCP port 80?",
        "options": ["ss -tlnp", "free -h", "du -sh", "lsblk -f"],
        "answer": "ss -tlnp",
        "explanation": "ss with TCP, listening, numeric, and process flags shows the listener and owner.",
        "points": 10,
    },
    {
        "id": "Q012",
        "level": "Intermediate",
        "topic": "Network",
        "question": "A ping fails but curl to the service works. What is the best conclusion?",
        "options": [
            "ICMP may be blocked while the service is reachable",
            "The disk is full",
            "DNS must be broken",
            "The service is definitely down",
        ],
        "answer": "ICMP may be blocked while the service is reachable",
        "explanation": "Ping tests ICMP, not the application protocol.",
        "points": 10,
    },
    {
        "id": "Q013",
        "level": "Intermediate",
        "topic": "DNS",
        "question": "Which command queries a specific DNS resolver?",
        "options": ["dig @8.8.8.8 example.com", "ping -u example.com", "df @8.8.8.8", "chmod dns"],
        "answer": "dig @8.8.8.8 example.com",
        "explanation": "The @server syntax directs dig to a selected resolver.",
        "points": 10,
    },
    {
        "id": "Q014",
        "level": "Intermediate",
        "topic": "Permissions",
        "question": "A service needs read access through its group. Which mode is a reasonable starting point for a non-executable config file?",
        "options": ["640", "777", "111", "000"],
        "answer": "640",
        "explanation": "640 gives owner read/write and group read access, with no access for others.",
        "points": 10,
    },
    {
        "id": "Q015",
        "level": "Intermediate",
        "topic": "Files",
        "question": "What safety step should precede find ... -delete?",
        "options": [
            "Run the same match with -print first",
            "Run it from / without filters",
            "Add sudo automatically",
            "Disable logging",
        ],
        "answer": "Run the same match with -print first",
        "explanation": "Previewing exact matches reduces accidental deletion.",
        "points": 10,
    },
    {
        "id": "Q016",
        "level": "Intermediate",
        "topic": "Backup",
        "question": "Which tar flag lists archive contents without extraction?",
        "options": ["-t", "-c", "-x", "-z"],
        "answer": "-t",
        "explanation": "The -t operation lists archive members.",
        "points": 10,
    },
    {
        "id": "Q017",
        "level": "Advanced",
        "topic": "Performance",
        "question": "High load and high I/O wait with idle CPU most strongly suggests what?",
        "options": ["Processes blocked on I/O", "DNS cache success", "Excess free memory", "A healthy storage path"],
        "answer": "Processes blocked on I/O",
        "explanation": "Load includes tasks waiting for uninterruptible I/O, not only active CPU work.",
        "points": 15,
    },
    {
        "id": "Q018",
        "level": "Advanced",
        "topic": "Performance",
        "question": "Why should vmstat be sampled more than once?",
        "options": [
            "The first row may be an average since boot",
            "It changes file ownership",
            "It queries DNS",
            "It restarts the kernel",
        ],
        "answer": "The first row may be an average since boot",
        "explanation": "Repeated interval samples better represent current behaviour.",
        "points": 15,
    },
    {
        "id": "Q019",
        "level": "Advanced",
        "topic": "Storage",
        "question": "Which iostat field often indicates device saturation when persistently near 100%?",
        "options": ["%util", "ttl", "inode", "PID"],
        "answer": "%util",
        "explanation": "%util approximates how busy a device is; it must be interpreted with latency and queue metrics.",
        "points": 15,
    },
    {
        "id": "Q020",
        "level": "Advanced",
        "topic": "Containers",
        "question": "A container is missing from docker ps. What is the next low-risk command?",
        "options": ["docker ps -a", "rm -rf /var/lib/docker", "docker system prune -a --volumes", "reboot"],
        "answer": "docker ps -a",
        "explanation": "The default command shows running containers only; -a includes exited containers.",
        "points": 15,
    },
    {
        "id": "Q021",
        "level": "Advanced",
        "topic": "Containers",
        "question": "Which command inspects the last 100 log lines for container app?",
        "options": [
            "docker logs --tail 100 app",
            "journalctl -u docker --delete app",
            "tail docker app",
            "ss --logs app",
        ],
        "answer": "docker logs --tail 100 app",
        "explanation": "docker logs reads container stdout and stderr, and --tail limits output.",
        "points": 15,
    },
    {
        "id": "Q022",
        "level": "Advanced",
        "topic": "Firewall",
        "question": "Before enabling a remote firewall, what must be verified?",
        "options": [
            "The management access rule exists",
            "All ports are open",
            "The root filesystem is world-writable",
            "Docker storage is deleted",
        ],
        "answer": "The management access rule exists",
        "explanation": "Remote administration access must be explicitly preserved before enforcing firewall policy.",
        "points": 15,
    },
    {
        "id": "Q023",
        "level": "Advanced",
        "topic": "Troubleshooting",
        "question": "Why is rebooting usually a weak first diagnostic action?",
        "options": [
            "It destroys transient evidence and may only hide the symptom",
            "It always deletes the filesystem",
            "It changes DNS ownership",
            "It permanently disables the network",
        ],
        "answer": "It destroys transient evidence and may only hide the symptom",
        "explanation": "A reboot can clear observable state without identifying the underlying fault.",
        "points": 15,
    },
    {
        "id": "Q024",
        "level": "Advanced",
        "topic": "Troubleshooting",
        "question": "Which sequence is strongest for a failed web service?",
        "options": [
            "status → logs → config validation → targeted change → test",
            "reboot → chmod 777 → delete logs",
            "disable firewall → restart repeatedly",
            "delete package → format disk",
        ],
        "answer": "status → logs → config validation → targeted change → test",
        "explanation": "The sequence gathers evidence, validates the suspected cause, limits change scope, and verifies recovery.",
        "points": 15,
    },
]

# Additional assessment questions for v1.3.0
EXERCISES.extend(
    [
        {
            "id": "Q025",
            "level": "Beginner",
            "topic": "Files",
            "question": "Which command shows detailed metadata including permissions and timestamps?",
            "options": ["stat file.txt", "pwd", "ping", "free -h"],
            "answer": "stat file.txt",
            "explanation": "stat reports file metadata such as mode, owner, size, and timestamps.",
            "points": 5,
        },
        {
            "id": "Q026",
            "level": "Beginner",
            "topic": "Text",
            "question": "Which command displays only the first 20 lines of a file?",
            "options": ["head -n 20 file.log", "tail -f file.log", "df -h", "ip route"],
            "answer": "head -n 20 file.log",
            "explanation": "head reads from the beginning of a file and -n selects the line count.",
            "points": 5,
        },
        {
            "id": "Q027",
            "level": "Beginner",
            "topic": "Text",
            "question": "Which pipeline counts repeated adjacent lines after sorting?",
            "options": ["sort names.txt | uniq -c", "cat names.txt | rm", "df -i | ping", "chmod 777 names.txt"],
            "answer": "sort names.txt | uniq -c",
            "explanation": "uniq counts adjacent duplicates, so sorting first groups identical records.",
            "points": 5,
        },
        {
            "id": "Q028",
            "level": "Beginner",
            "topic": "Shell",
            "question": "Which command explains whether ls is an alias, builtin, or executable?",
            "options": ["type -a ls", "whereis /var/log", "du -sh ls", "journalctl -u ls"],
            "answer": "type -a ls",
            "explanation": "type reports how the current shell resolves a command name.",
            "points": 5,
        },
        {
            "id": "Q029",
            "level": "Beginner",
            "topic": "Users",
            "question": "Which command shows a user ID and group memberships?",
            "options": ["id analyst", "whoami analyst", "df analyst", "tail analyst"],
            "answer": "id analyst",
            "explanation": "id reports UID, primary GID, and supplementary groups.",
            "points": 5,
        },
        {
            "id": "Q030",
            "level": "Beginner",
            "topic": "Files",
            "question": "What is the safest first step before using rm recursively?",
            "options": [
                "Confirm the exact target with pwd and ls",
                "Add -f immediately",
                "Run from /",
                "Disable backups",
            ],
            "answer": "Confirm the exact target with pwd and ls",
            "explanation": "Verifying location and target reduces accidental recursive deletion.",
            "points": 5,
        },
        {
            "id": "Q031",
            "level": "Beginner",
            "topic": "Text",
            "question": "Which command compares two text files in unified format?",
            "options": ["diff -u old.conf new.conf", "cmp -r /", "free -u", "ss -u"],
            "answer": "diff -u old.conf new.conf",
            "explanation": "diff -u produces a readable unified comparison suitable for configuration review.",
            "points": 5,
        },
        {
            "id": "Q032",
            "level": "Intermediate",
            "topic": "Processes",
            "question": "Which signal usually requests graceful termination?",
            "options": ["SIGTERM", "SIGKILL", "SIGSTOP", "SIGCONT"],
            "answer": "SIGTERM",
            "explanation": "SIGTERM allows a process to handle shutdown and clean up resources.",
            "points": 10,
        },
        {
            "id": "Q033",
            "level": "Intermediate",
            "topic": "Permissions",
            "question": "Which command displays POSIX ACL entries?",
            "options": ["getfacl /srv/shared", "chmod 777 /srv/shared", "df -i /srv/shared", "ping /srv/shared"],
            "answer": "getfacl /srv/shared",
            "explanation": "getfacl shows access and default ACL entries without changing them.",
            "points": 10,
        },
        {
            "id": "Q034",
            "level": "Intermediate",
            "topic": "Network",
            "question": "Which command shows the route the kernel would use to reach 10.0.0.5?",
            "options": ["ip route get 10.0.0.5", "ip neigh flush all", "rm /etc/resolv.conf", "ss -K dst 10.0.0.5"],
            "answer": "ip route get 10.0.0.5",
            "explanation": "ip route get returns the selected route, interface, gateway, and source address.",
            "points": 10,
        },
        {
            "id": "Q035",
            "level": "Intermediate",
            "topic": "Storage",
            "question": "Which command identifies the mount containing /var/log?",
            "options": ["findmnt -T /var/log", "find /var/log -delete", "umount /var/log", "mkfs /var/log"],
            "answer": "findmnt -T /var/log",
            "explanation": "findmnt -T maps a path to its containing mount safely.",
            "points": 10,
        },
        {
            "id": "Q036",
            "level": "Intermediate",
            "topic": "Scheduling",
            "question": "Why can a command work interactively but fail in cron?",
            "options": [
                "Cron may have a smaller PATH and environment",
                "Cron always runs as root",
                "Cron disables filesystems",
                "Cron changes DNS records",
            ],
            "answer": "Cron may have a smaller PATH and environment",
            "explanation": "Scheduled jobs often run with a minimal environment and should use absolute paths.",
            "points": 10,
        },
        {
            "id": "Q037",
            "level": "Intermediate",
            "topic": "Network",
            "question": "Which command checks TCP port 443 without sending application data?",
            "options": ["nc -vz host.example 443", "df -h host.example", "chmod 443 host.example", "free -443"],
            "answer": "nc -vz host.example 443",
            "explanation": "nc with -z and -v tests whether a TCP connection can be established.",
            "points": 10,
        },
        {
            "id": "Q038",
            "level": "Intermediate",
            "topic": "Users",
            "question": "Which command lists a user password lock status?",
            "options": ["passwd -S analyst", "cat analyst", "ping analyst", "du -S analyst"],
            "answer": "passwd -S analyst",
            "explanation": "passwd -S reports whether the password is usable, locked, or otherwise configured.",
            "points": 10,
        },
        {
            "id": "Q039",
            "level": "Advanced",
            "topic": "Diagnostics",
            "question": "Which strace option follows child processes?",
            "options": ["-f", "-n", "-z", "-h"],
            "answer": "-f",
            "explanation": "The -f option follows forked or cloned child processes.",
            "points": 15,
        },
        {
            "id": "Q040",
            "level": "Advanced",
            "topic": "Performance",
            "question": "What does consistently high CPU steal time indicate in a VM?",
            "options": [
                "The hypervisor is withholding CPU time",
                "The disk is empty",
                "DNS is healthy",
                "The firewall is disabled",
            ],
            "answer": "The hypervisor is withholding CPU time",
            "explanation": "Steal time is guest-visible time when the virtual CPU waits for the hypervisor.",
            "points": 15,
        },
        {
            "id": "Q041",
            "level": "Advanced",
            "topic": "Security",
            "question": "Which restorecon option previews changes without applying them?",
            "options": ["-n", "-f", "-x", "-k"],
            "answer": "-n",
            "explanation": "The -n option performs a dry run so context changes can be reviewed.",
            "points": 15,
        },
        {
            "id": "Q042",
            "level": "Advanced",
            "topic": "TLS",
            "question": "Why is -servername useful with openssl s_client?",
            "options": [
                "It sends SNI for the intended virtual host",
                "It changes the system hostname",
                "It disables certificates",
                "It opens every port",
            ],
            "answer": "It sends SNI for the intended virtual host",
            "explanation": "SNI is required to test the certificate selected for a specific hostname on shared TLS endpoints.",
            "points": 15,
        },
        {
            "id": "Q043",
            "level": "Advanced",
            "topic": "Containers",
            "question": "Which command shows a one-time container resource snapshot?",
            "options": ["docker stats --no-stream", "docker rm -f", "docker system prune -a", "docker exec reboot"],
            "answer": "docker stats --no-stream",
            "explanation": "--no-stream returns one CPU, memory, and I/O sample rather than a continuous display.",
            "points": 15,
        },
        {
            "id": "Q044",
            "level": "Advanced",
            "topic": "Firewall",
            "question": "What is the safest way to validate an nftables file before applying it?",
            "options": ["nft -c -f rules.nft", "nft flush ruleset", "iptables -F", "reboot"],
            "answer": "nft -c -f rules.nft",
            "explanation": "The check option validates syntax and semantics without replacing the active ruleset.",
            "points": 15,
        },
        {
            "id": "Q045",
            "level": "Advanced",
            "topic": "Resources",
            "question": "Which command inspects limits for a running PID?",
            "options": ["prlimit --pid 2142", "ulimit in another shell", "df --pid 2142", "ping 2142"],
            "answer": "prlimit --pid 2142",
            "explanation": "prlimit reads the resource limits applied to the selected running process.",
            "points": 15,
        },
    ]
)


def exercises_for_level(level: str) -> list[Exercise]:
    return [item for item in EXERCISES if item["level"] == level]
