from __future__ import annotations

Incident = dict[str, object]

INCIDENTS: list[Incident] = [
    {
        "id": "INC-001",
        "level": "Beginner",
        "category": "Disk",
        "title": "Application cannot write new log entries",
        "brief": "The API is running, but new requests fail when it attempts to write logs.",
        "symptoms": [
            "HTTP 500 responses started recently",
            "The service is still active",
            "Log writes report no space left on device",
        ],
        "evidence": ["/data is 97% full", "/var/log is only 42% full", "A 36 GB archive exists under /data/backups"],
        "question": "Which command should be used first to verify filesystem capacity?",
        "options": ["df -h", "free -h", "ss -tulnp", "systemctl restart api"],
        "answer": "df -h",
        "points": 10,
        "root_cause": "The /data filesystem is full because old backup archives were retained.",
        "remediation": [
            "Confirm the large files with du or find",
            "Verify retention requirements",
            "Archive or remove approved old backups",
            "Add monitoring before the filesystem reaches the alert threshold",
        ],
        "unsafe_action": "Restarting the application repeatedly will not free disk space and may increase log volume.",
    },
    {
        "id": "INC-002",
        "level": "Beginner",
        "category": "Services",
        "title": "Web service is not responding after deployment",
        "brief": "The deployment completed, but the web endpoint returns connection refused.",
        "symptoms": ["Browser cannot connect", "The host responds to ping", "Deployment changed nginx configuration"],
        "evidence": [
            "nginx.service is failed",
            "The journal reports an invalid directive",
            "No process is listening on port 80",
        ],
        "question": "What is the safest first diagnostic command?",
        "options": ["systemctl status nginx", "chmod -R 777 /etc/nginx", "reboot", "rm /etc/nginx/nginx.conf"],
        "answer": "systemctl status nginx",
        "points": 10,
        "root_cause": "A syntax error in the new nginx configuration prevents the service from starting.",
        "remediation": [
            "Inspect service status",
            "Read nginx journal entries",
            "Validate configuration syntax",
            "Restore or correct the invalid directive",
            "Start the service and test the endpoint",
        ],
        "unsafe_action": "Changing all permissions or deleting the configuration destroys evidence and introduces new problems.",
    },
    {
        "id": "INC-003",
        "level": "Beginner",
        "category": "Memory",
        "title": "Server feels slow during report generation",
        "brief": "Users report delays while a scheduled report is running.",
        "symptoms": ["Latency increases for ten minutes", "The process remains responsive", "Disk capacity is normal"],
        "evidence": [
            "Available memory falls below 300 MiB",
            "Swap usage rises",
            "A report process consumes 58% memory",
        ],
        "question": "Which command gives the clearest first memory summary?",
        "options": ["free -h", "df -h", "dig example.com", "tar -czf backup.tar.gz /"],
        "answer": "free -h",
        "points": 10,
        "root_cause": "A report process creates memory pressure and swap activity.",
        "remediation": [
            "Confirm memory pressure",
            "Identify the process with ps or top",
            "Review report limits and scheduling",
            "Set memory controls where appropriate",
        ],
        "unsafe_action": "Killing the largest process without confirming its purpose may corrupt an active report or transaction.",
    },
    {
        "id": "INC-004",
        "level": "Intermediate",
        "category": "Network",
        "title": "API works locally but not from another host",
        "brief": "A health request succeeds on the server but remote clients cannot connect.",
        "symptoms": ["curl localhost:8000 succeeds", "Remote connection times out", "DNS resolves correctly"],
        "evidence": [
            "The API listens on 127.0.0.1:8000",
            "No public listener exists on port 8000",
            "Firewall permits the approved application port",
        ],
        "question": "Which command best confirms the listener address?",
        "options": ["ss -tulnp", "du -sh /var", "free -h", "journalctl --vacuum-time=1d"],
        "answer": "ss -tulnp",
        "points": 15,
        "root_cause": "The API is bound only to the loopback interface.",
        "remediation": [
            "Confirm the listener",
            "Check application bind configuration",
            "Bind to the approved interface",
            "Restart through the service manager",
            "Retest locally and remotely",
        ],
        "unsafe_action": "Disabling the firewall would broaden exposure without fixing the loopback-only listener.",
    },
    {
        "id": "INC-005",
        "level": "Intermediate",
        "category": "DNS",
        "title": "Hostname fails but direct IP access works",
        "brief": "The service responds by IP address, but its hostname does not resolve on one server.",
        "symptoms": [
            "curl to the IP succeeds",
            "curl to the hostname reports resolution failure",
            "Other servers resolve the hostname",
        ],
        "evidence": [
            "The affected server uses an old resolver",
            "The resolver times out",
            "The authoritative DNS record is correct",
        ],
        "question": "Which command should directly test DNS resolution?",
        "options": ["dig api.example.com", "df -i", "systemctl restart ssh", "chmod +x /etc/resolv.conf"],
        "answer": "dig api.example.com",
        "points": 15,
        "root_cause": "The affected host is configured with an unavailable DNS resolver.",
        "remediation": [
            "Query the configured resolver",
            "Compare with an approved resolver",
            "Correct resolver configuration",
            "Retest the application hostname",
        ],
        "unsafe_action": "Changing file execute permissions does not repair DNS configuration.",
    },
    {
        "id": "INC-006",
        "level": "Intermediate",
        "category": "Permissions",
        "title": "Service cannot read its configuration",
        "brief": "A service starts under appuser and exits with permission denied.",
        "symptoms": [
            "The configuration file exists",
            "The service account is appuser",
            "The deployment copied the file as root",
        ],
        "evidence": ["File owner is root:root", "Mode is 600", "The application only needs read access"],
        "question": "Which command first shows owner and mode together?",
        "options": ["ls -l /opt/app/config.ini", "ping -c 4 localhost", "df -h", "docker ps"],
        "answer": "ls -l /opt/app/config.ini",
        "points": 15,
        "root_cause": "The deployment created a root-owned mode-600 file that appuser cannot read.",
        "remediation": [
            "Verify expected service account",
            "Choose least-privilege owner/group and mode",
            "Apply a targeted chown or chmod",
            "Restart and verify logs",
        ],
        "unsafe_action": "chmod 777 would fix access by granting excessive permissions to every user.",
    },
    {
        "id": "INC-007",
        "level": "Intermediate",
        "category": "Logs",
        "title": "Intermittent HTTP 502 responses",
        "brief": "Most requests succeed, but some users receive gateway errors.",
        "symptoms": ["nginx remains active", "Errors occur in short bursts", "The upstream API is managed by systemd"],
        "evidence": [
            "nginx reports upstream timed out",
            "API logs show database timeouts",
            "CPU and disk are within normal ranges",
        ],
        "question": "Which command best narrows API logs to the recent incident window?",
        "options": [
            "journalctl -u api --since '15 minutes ago'",
            "chmod -R 777 /var/log",
            "ufw disable",
            "tar -xzf unknown.tar.gz -C /",
        ],
        "answer": "journalctl -u api --since '15 minutes ago'",
        "points": 15,
        "root_cause": "Database connection delays cause the API upstream to exceed nginx timeout limits.",
        "remediation": [
            "Correlate nginx and API timestamps",
            "Inspect database latency and pool state",
            "Correct the database bottleneck",
            "Review timeout values only after root cause is understood",
        ],
        "unsafe_action": "Increasing every timeout can hide the symptom while allowing resource queues to grow.",
    },
    {
        "id": "INC-008",
        "level": "Advanced",
        "category": "Performance",
        "title": "High load with moderate CPU utilisation",
        "brief": "Load average rises above 10, but CPU idle remains around 45%.",
        "symptoms": ["Requests stall", "CPU is not saturated", "Storage latency warnings appear"],
        "evidence": ["vmstat shows blocked processes", "I/O wait is 28%", "iostat reports sda at 99% utilisation"],
        "question": "Which command provides extended per-device I/O metrics?",
        "options": ["iostat -xz 1 3", "cat /etc/os-release", "dig +short example.com", "chown -R root:root /"],
        "answer": "iostat -xz 1 3",
        "points": 20,
        "root_cause": "The primary block device is saturated, leaving processes blocked on I/O.",
        "remediation": [
            "Confirm repeated I/O samples",
            "Identify the workload generating I/O",
            "Reduce or reschedule the workload",
            "Evaluate storage capacity and architecture",
        ],
        "unsafe_action": "Adding CPU does not solve a saturated storage device.",
    },
    {
        "id": "INC-009",
        "level": "Advanced",
        "category": "Containers",
        "title": "Application container exits immediately",
        "brief": "A newly deployed container starts and exits with status 1.",
        "symptoms": [
            "Container is absent from the default running list",
            "Image pull succeeded",
            "Database container is running",
        ],
        "evidence": [
            "docker ps -a shows Exited (1)",
            "Container logs show connection refused to postgres:5432",
            "Both containers are attached to different networks",
        ],
        "question": "Which command should be used after confirming the exited state?",
        "options": ["docker logs --tail 100 app", "rm -rf /var/lib/docker", "ufw disable", "reboot"],
        "answer": "docker logs --tail 100 app",
        "points": 20,
        "root_cause": "The application container cannot reach the database because they are on different Docker networks.",
        "remediation": [
            "Read container logs",
            "Inspect container network attachments",
            "Attach services to the intended network",
            "Restart the application and verify health",
        ],
        "unsafe_action": "Deleting Docker storage can destroy images, containers, and volumes without addressing network configuration.",
    },
    {
        "id": "INC-010",
        "level": "Advanced",
        "category": "Security",
        "title": "SSH access fails after firewall change",
        "brief": "A firewall policy was enabled remotely and new SSH sessions cannot connect.",
        "symptoms": [
            "Existing console access is available",
            "The server responds to application traffic",
            "SSH previously used port 22",
        ],
        "evidence": [
            "UFW is active",
            "No allow rule exists for the administration subnet",
            "ss confirms sshd listens on port 22",
        ],
        "question": "Which command should inspect numbered firewall rules?",
        "options": ["ufw status numbered", "chmod 777 /etc/ssh/sshd_config", "kill -9 1", "find / -delete"],
        "answer": "ufw status numbered",
        "points": 20,
        "root_cause": "The firewall was enabled without an SSH allow rule for the administration network.",
        "remediation": [
            "Use console access",
            "Inspect numbered rules",
            "Add the narrow approved SSH rule",
            "Test a second session before closing console access",
            "Document the change",
        ],
        "unsafe_action": "Disabling all security controls may restore access but creates unnecessary exposure.",
    },
]

# Expanded incident catalogue for the free public beta (v1.3.0)
INCIDENTS.extend(
    [
        {
            "id": "INC-011",
            "level": "Beginner",
            "category": "Storage",
            "title": "Filesystem has free space but cannot create files",
            "brief": "The application reports no space left even though capacity is below 70%.",
            "symptoms": [
                "New files cannot be created",
                "Existing files can still be read",
                "Disk capacity is not near full",
            ],
            "evidence": [
                "Inode use on /var is 100%",
                "Millions of tiny cache files exist",
                "Other filesystems have free inodes",
            ],
            "question": "Which command checks inode usage first?",
            "options": ["df -i", "free -h", "ping -c 4 localhost", "systemctl restart app"],
            "answer": "df -i",
            "points": 10,
            "root_cause": "The /var filesystem has exhausted its available inodes.",
            "remediation": [
                "Confirm inode use",
                "Find directories containing very large file counts",
                "Remove only approved stale files",
                "Add inode monitoring",
            ],
            "unsafe_action": "Deleting random large files may not free any inodes if the problem is millions of tiny files.",
        },
        {
            "id": "INC-012",
            "level": "Beginner",
            "category": "Processes",
            "title": "One process consumes nearly all CPU",
            "brief": "The server becomes slow while a data conversion job runs.",
            "symptoms": ["CPU remains above 95%", "Memory is stable", "The issue begins when the job starts"],
            "evidence": [
                "One PID uses 92% CPU",
                "Other processes use less than 5%",
                "Load falls when the job completes",
            ],
            "question": "Which command gives a live process overview?",
            "options": ["top", "df -h", "dig example.com", "mount -a"],
            "answer": "top",
            "points": 10,
            "root_cause": "A data conversion process is saturating a CPU core.",
            "remediation": [
                "Capture top output",
                "Identify the PID and owner",
                "Confirm whether the workload is expected",
                "Adjust scheduling or optimise the job",
            ],
            "unsafe_action": "Killing the process immediately can lose work and does not explain why it consumes CPU.",
        },
        {
            "id": "INC-013",
            "level": "Beginner",
            "category": "Services",
            "title": "Background service is inactive after reboot",
            "brief": "A monitoring agent worked yesterday but is not running after a restart.",
            "symptoms": ["No new monitoring data arrives", "The host is reachable", "The agent binary exists"],
            "evidence": ["systemctl reports inactive", "The unit is disabled", "The last manual start was successful"],
            "question": "Which command checks the service state?",
            "options": [
                "systemctl status monitoring-agent",
                "rm -rf /etc/systemd",
                "chmod 777 /usr/bin/agent",
                "reboot",
            ],
            "answer": "systemctl status monitoring-agent",
            "points": 10,
            "root_cause": "The unit was never enabled to start at boot.",
            "remediation": [
                "Inspect unit status",
                "Read the previous boot logs",
                "Enable the unit if policy requires it",
                "Start and verify data delivery",
            ],
            "unsafe_action": "Repeated reboots do not correct a disabled unit and delay diagnosis.",
        },
        {
            "id": "INC-014",
            "level": "Beginner",
            "category": "Logs",
            "title": "A log search returns too many unrelated lines",
            "brief": "An operator searches for error and receives thousands of historical matches.",
            "symptoms": [
                "The file is several gigabytes",
                "Only the last ten minutes matter",
                "The service name is known",
            ],
            "evidence": [
                "Recent entries have timestamps",
                "The pattern appears in multiple services",
                "The incident ID is present in relevant lines",
            ],
            "question": "Which command narrows recent matching lines safely?",
            "options": [
                "tail -n 500 /var/log/syslog | grep 'INC-42'",
                "grep -r error /",
                "rm /var/log/syslog",
                "journalctl --vacuum-size=1M",
            ],
            "answer": "tail -n 500 /var/log/syslog | grep 'INC-42'",
            "points": 10,
            "root_cause": "The original search lacked a time or volume boundary and a specific identifier.",
            "remediation": [
                "Limit the input window",
                "Filter using the incident identifier",
                "Inspect context around matches",
                "Save relevant evidence",
            ],
            "unsafe_action": "Deleting or vacuuming logs removes evidence rather than improving the search.",
        },
        {
            "id": "INC-015",
            "level": "Beginner",
            "category": "Permissions",
            "title": "Shell script will not execute",
            "brief": "A deployment script exists but the shell reports permission denied.",
            "symptoms": ["The file can be read", "The shebang is valid", "Execution fails immediately"],
            "evidence": [
                "ls -l shows mode 0644",
                "The owner is correct",
                "The filesystem is mounted with execution allowed",
            ],
            "question": "Which command adds execute permission for the owner?",
            "options": ["chmod u+x deploy.sh", "chmod 777 /", "chown -R root:root /", "rm deploy.sh"],
            "answer": "chmod u+x deploy.sh",
            "points": 10,
            "root_cause": "The script lacks the owner execute bit.",
            "remediation": [
                "Verify the file and owner",
                "Add only the required execute bit",
                "Run a syntax check",
                "Execute in a controlled environment",
            ],
            "unsafe_action": "Using 777 grants unnecessary write and execute access to every user.",
        },
        {
            "id": "INC-016",
            "level": "Beginner",
            "category": "Files",
            "title": "Configuration file is missing from the expected path",
            "brief": "A service startup message says /opt/app/config.yml does not exist.",
            "symptoms": [
                "The package is installed",
                "A previous version used another directory",
                "No permission error appears",
            ],
            "evidence": [
                "find locates config.yml under /etc/opsready",
                "The service unit still references /opt/app",
                "The file contents are valid",
            ],
            "question": "Which command safely searches for the file?",
            "options": ["find /etc /opt -name config.yml -type f", "rm -rf /opt/app", "chmod -R 777 /etc", "kill -9 1"],
            "answer": "find /etc /opt -name config.yml -type f",
            "points": 10,
            "root_cause": "The deployment moved the configuration but did not update the service path.",
            "remediation": [
                "Search controlled directories",
                "Confirm the intended configuration location",
                "Update the unit or deploy the file",
                "Restart and verify",
            ],
            "unsafe_action": "Searching from / with destructive actions or broad permission changes creates unnecessary risk.",
        },
        {
            "id": "INC-017",
            "level": "Beginner",
            "category": "Network",
            "title": "Server can reach IP addresses but not websites",
            "brief": "Ping to a public IP succeeds while hostnames fail.",
            "symptoms": ["Network interface is up", "Default route exists", "Name-based commands fail"],
            "evidence": [
                "ping 1.1.1.1 succeeds",
                "dig reports no servers could be reached",
                "resolv.conf references an unavailable resolver",
            ],
            "question": "Which command tests the configured DNS path?",
            "options": ["dig example.com", "df -h", "free -h", "systemctl restart nginx"],
            "answer": "dig example.com",
            "points": 10,
            "root_cause": "The configured DNS resolver is unavailable.",
            "remediation": [
                "Query the configured resolver",
                "Compare an approved resolver",
                "Correct resolver settings",
                "Retest the hostname",
            ],
            "unsafe_action": "Restarting unrelated services will not repair name resolution.",
        },
        {
            "id": "INC-018",
            "level": "Beginner",
            "category": "Network",
            "title": "Web port is not listening",
            "brief": "The host is reachable but clients receive connection refused on port 8080.",
            "symptoms": ["Ping succeeds", "The application is expected on 8080", "Firewall logs show no drops"],
            "evidence": [
                "ss shows no listener on 8080",
                "The process list lacks the application",
                "The deployment ended with an error",
            ],
            "question": "Which command checks local listening sockets?",
            "options": ["ss -tlnp", "du -sh /var", "date -u", "tar -tf backup.tar"],
            "answer": "ss -tlnp",
            "points": 10,
            "root_cause": "The application process did not start, so no local socket is listening.",
            "remediation": [
                "Check the listener",
                "Inspect service status and logs",
                "Correct the startup failure",
                "Retest locally before remote access",
            ],
            "unsafe_action": "Opening the firewall cannot help when no process is listening.",
        },
        {
            "id": "INC-019",
            "level": "Beginner",
            "category": "Time",
            "title": "Log timestamps appear one hour wrong",
            "brief": "Events are difficult to correlate because the server time zone is incorrect.",
            "symptoms": [
                "Clock minutes are accurate",
                "The displayed zone is UTC instead of local time",
                "NTP is synchronised",
            ],
            "evidence": [
                "date shows UTC",
                "timedatectl reports the wrong time zone",
                "Other servers use Europe/Madrid",
            ],
            "question": "Which command displays the current date and zone?",
            "options": ["date -Is", "rm /etc/localtime", "killall systemd-timesyncd", "chmod 777 /etc"],
            "answer": "date -Is",
            "points": 10,
            "root_cause": "The system uses a different time zone from the operational standard.",
            "remediation": [
                "Record current time and zone",
                "Inspect timedatectl",
                "Set the approved time zone",
                "Verify logs and applications",
            ],
            "unsafe_action": "Deleting time-zone files or stopping time synchronisation can create larger timing errors.",
        },
        {
            "id": "INC-020",
            "level": "Beginner",
            "category": "Users",
            "title": "Operator cannot access a shared directory",
            "brief": "A user receives permission denied when entering /srv/reports.",
            "symptoms": ["The directory exists", "Other group members can access it", "The user was recently added"],
            "evidence": [
                "id does not list the reports group",
                "Directory group is reports",
                "Group permissions allow access",
            ],
            "question": "Which command confirms the user group memberships?",
            "options": ["id analyst", "chmod 777 /srv/reports", "rm -rf /srv/reports", "reboot"],
            "answer": "id analyst",
            "points": 10,
            "root_cause": "The user session does not have membership in the required reports group.",
            "remediation": [
                "Check identity and groups",
                "Add the user through the approved process",
                "Start a new login session",
                "Verify least-privilege access",
            ],
            "unsafe_action": "Changing the directory to 777 bypasses group governance and exposes reports.",
        },
        {
            "id": "INC-021",
            "level": "Beginner",
            "category": "Archives",
            "title": "Backup archive cannot be opened",
            "brief": "A downloaded .tar.gz file produces an unexpected end-of-file error.",
            "symptoms": [
                "The file size is smaller than expected",
                "The download was interrupted",
                "The source checksum is available",
            ],
            "evidence": [
                "sha256sum differs from the published value",
                "tar integrity test fails",
                "Network log shows a disconnect",
            ],
            "question": "Which command should verify the file checksum?",
            "options": ["sha256sum backup.tar.gz", "chmod 777 backup.tar.gz", "systemctl restart ssh", "df -i"],
            "answer": "sha256sum backup.tar.gz",
            "points": 10,
            "root_cause": "The archive is incomplete or corrupted during transfer.",
            "remediation": [
                "Calculate the checksum",
                "Compare with the trusted value",
                "Download again through a reliable path",
                "Test the archive before extraction",
            ],
            "unsafe_action": "Forcing extraction of a corrupt archive can create partial or misleading files.",
        },
        {
            "id": "INC-022",
            "level": "Beginner",
            "category": "Storage",
            "title": "Expected backup disk is not mounted",
            "brief": "A backup job writes into an empty local directory instead of the external disk.",
            "symptoms": [
                "The directory exists",
                "Backup size consumes the root filesystem",
                "The external device is connected",
            ],
            "evidence": [
                "findmnt shows no mount at /mnt/backup",
                "lsblk shows the device",
                "The job does not verify the mount",
            ],
            "question": "Which command confirms what is mounted at the path?",
            "options": ["findmnt -T /mnt/backup", "rm -rf /mnt/backup", "chmod 777 /mnt/backup", "kill -9 1"],
            "answer": "findmnt -T /mnt/backup",
            "points": 10,
            "root_cause": "The backup filesystem was not mounted, so data was written to the underlying directory.",
            "remediation": [
                "Stop the backup job",
                "Confirm device and filesystem identity",
                "Mount through the approved configuration",
                "Add a preflight mount check",
            ],
            "unsafe_action": "Deleting the directory may remove locally written backups without mounting the intended device.",
        },
        {
            "id": "INC-023",
            "level": "Beginner",
            "category": "Shell",
            "title": "A different program runs than expected",
            "brief": "Typing python launches an old interpreter from a custom directory.",
            "symptoms": ["python3 is current", "PATH was modified", "The command name has multiple matches"],
            "evidence": [
                "type -a python shows an alias and two paths",
                "which returns the custom path",
                "The alias was added to a profile",
            ],
            "question": "Which command explains every interpretation of the name?",
            "options": ["type -a python", "df -h", "ss -s", "journalctl -b"],
            "answer": "type -a python",
            "points": 10,
            "root_cause": "A shell alias and PATH order select the old interpreter.",
            "remediation": [
                "Inspect aliases and paths",
                "Remove or update the obsolete profile entry",
                "Start a new shell",
                "Verify the resolved interpreter",
            ],
            "unsafe_action": "Deleting interpreter binaries can break applications and package management.",
        },
        {
            "id": "INC-024",
            "level": "Beginner",
            "category": "Files",
            "title": "Application reads an old symbolic-link target",
            "brief": "A current link still points to the previous release directory.",
            "symptoms": [
                "The new release exists",
                "The service follows /opt/app/current",
                "Restarting does not change the target",
            ],
            "evidence": [
                "readlink shows /opt/app/releases/41",
                "Release 42 is healthy",
                "The link was not updated during deployment",
            ],
            "question": "Which command shows the resolved link target?",
            "options": ["readlink -f /opt/app/current", "rm -rf /opt/app/current", "chmod 777 /opt/app", "reboot"],
            "answer": "readlink -f /opt/app/current",
            "points": 10,
            "root_cause": "The deployment left the current symbolic link pointing at release 41.",
            "remediation": [
                "Inspect the link target",
                "Verify release 42",
                "Atomically update the link",
                "Restart and test rollback",
            ],
            "unsafe_action": "Removing the entire application path destroys both releases and rollback capability.",
        },
        {
            "id": "INC-025",
            "level": "Intermediate",
            "category": "Services",
            "title": "Service repeatedly restarts",
            "brief": "A worker alternates between activating and failed every few seconds.",
            "symptoms": ["CPU spikes briefly", "The unit restart counter increases", "Users see intermittent failures"],
            "evidence": [
                "systemctl shows auto-restart enabled",
                "journal reports a missing environment variable",
                "The executable itself exists",
            ],
            "question": "Which command filters recent unit logs?",
            "options": [
                "journalctl -u worker --since '10 minutes ago'",
                "ufw disable",
                "chmod -R 777 /opt",
                "rm /etc/systemd/system/worker.service",
            ],
            "answer": "journalctl -u worker --since '10 minutes ago'",
            "points": 15,
            "root_cause": "A required environment variable is absent, causing the worker to exit and systemd to restart it.",
            "remediation": [
                "Capture recent logs",
                "Inspect the unit environment source",
                "Restore the required value securely",
                "Restart once and verify stability",
            ],
            "unsafe_action": "Repeated manual restarts increase noise without correcting the configuration.",
        },
        {
            "id": "INC-026",
            "level": "Intermediate",
            "category": "Network",
            "title": "Packets leave through the wrong interface",
            "brief": "Traffic to a private subnet uses the default internet gateway.",
            "symptoms": [
                "The destination is reachable from another host",
                "Two interfaces are configured",
                "The application times out",
            ],
            "evidence": [
                "ip route get selects eth0",
                "The private gateway should use eth1",
                "No specific route exists",
            ],
            "question": "Which command shows the kernel route decision?",
            "options": ["ip route get 10.20.0.15", "ping -c 100 8.8.8.8", "rm /etc/resolv.conf", "docker system prune"],
            "answer": "ip route get 10.20.0.15",
            "points": 15,
            "root_cause": "A missing specific route sends private traffic through the default gateway.",
            "remediation": [
                "Inspect the route decision",
                "Confirm the intended gateway and source address",
                "Add the approved route",
                "Retest and persist configuration",
            ],
            "unsafe_action": "Changing DNS or clearing containers cannot correct the kernel route.",
        },
        {
            "id": "INC-027",
            "level": "Intermediate",
            "category": "Network",
            "title": "Intermittent local neighbour failures",
            "brief": "A host occasionally cannot reach another server on the same subnet.",
            "symptoms": ["No router is involved", "Failures recover after minutes", "Interface errors are low"],
            "evidence": ["ip neigh shows FAILED entries", "The peer address is correct", "A duplicate IP alert exists"],
            "question": "Which command inspects neighbour state?",
            "options": ["ip neigh show", "df -i", "journalctl --vacuum-time=1d", "chmod 777 /etc/hosts"],
            "answer": "ip neigh show",
            "points": 15,
            "root_cause": "A duplicate address causes unstable ARP neighbour resolution.",
            "remediation": [
                "Inspect neighbour entries",
                "Confirm MAC ownership from network records",
                "Remove the duplicate address",
                "Flush only the affected stale entry and retest",
            ],
            "unsafe_action": "Flushing all network configuration hides evidence and disrupts healthy traffic.",
        },
        {
            "id": "INC-028",
            "level": "Intermediate",
            "category": "Storage",
            "title": "Unmount command reports target is busy",
            "brief": "Maintenance requires detaching /mnt/archive, but unmount fails.",
            "symptoms": [
                "No user is intentionally working there",
                "A backup completed earlier",
                "The mount is healthy",
            ],
            "evidence": [
                "lsof shows a shell current directory under the mount",
                "A process has an open file",
                "No filesystem error exists",
            ],
            "question": "Which command identifies processes using the mount?",
            "options": ["lsof +D /mnt/archive", "umount -f /mnt/archive", "rm -rf /mnt/archive", "reboot"],
            "answer": "lsof +D /mnt/archive",
            "points": 15,
            "root_cause": "An operator shell and backup process still hold references inside the filesystem.",
            "remediation": [
                "Identify open files and working directories",
                "Stop or move approved processes",
                "Unmount normally",
                "Verify the mount is detached",
            ],
            "unsafe_action": "Forcing unmount can interrupt writes and risk data inconsistency.",
        },
        {
            "id": "INC-029",
            "level": "Intermediate",
            "category": "Memory",
            "title": "Swap use keeps growing",
            "brief": "The server is responsive at first but becomes progressively slower.",
            "symptoms": ["RAM use is high", "Swap-in and swap-out increase", "One Java process grows steadily"],
            "evidence": [
                "free shows low available memory",
                "vmstat shows sustained si and so",
                "The process RSS rises every hour",
            ],
            "question": "Which command samples swapping over time?",
            "options": ["vmstat 1 5", "df -h", "dig +short example.com", "iptables -F"],
            "answer": "vmstat 1 5",
            "points": 15,
            "root_cause": "A long-running Java process is leaking memory and causing swap thrashing.",
            "remediation": [
                "Collect repeated memory samples",
                "Confirm the growing process",
                "Capture application diagnostics",
                "Restart only with approval and correct the leak",
            ],
            "unsafe_action": "Disabling swap under pressure can trigger the OOM killer and a larger outage.",
        },
        {
            "id": "INC-030",
            "level": "Intermediate",
            "category": "Scheduling",
            "title": "Scheduled report never runs",
            "brief": "A crontab entry exists, but no report appears overnight.",
            "symptoms": [
                "Manual execution works",
                "The script uses relative paths",
                "Cron sends no visible terminal output",
            ],
            "evidence": [
                "cron logs show command not found",
                "PATH is minimal",
                "The script calls python without an absolute path",
            ],
            "question": "Which command lists the active user crontab?",
            "options": ["crontab -l", "systemctl disable cron", "chmod 777 /etc/crontab", "rm -rf /var/spool/cron"],
            "answer": "crontab -l",
            "points": 15,
            "root_cause": "The cron environment lacks the interactive-shell PATH required to find python.",
            "remediation": [
                "Review the exact crontab",
                "Use absolute paths and capture output",
                "Test with the same user and environment",
                "Verify the next scheduled run",
            ],
            "unsafe_action": "Broad permission changes or deleting spool files can remove valid schedules.",
        },
        {
            "id": "INC-031",
            "level": "Intermediate",
            "category": "TLS",
            "title": "Browser reports an expired certificate",
            "brief": "HTTPS worked yesterday but now displays a certificate date error.",
            "symptoms": ["TCP 443 is reachable", "The service process is healthy", "Only TLS clients fail"],
            "evidence": [
                "openssl shows notAfter in the past",
                "The hostname matches",
                "The chain was previously trusted",
            ],
            "question": "Which command inspects the live certificate dates?",
            "options": [
                "openssl s_client -connect site.example.com:443 -servername site.example.com",
                "ufw disable",
                "chmod 777 /etc/ssl",
                "killall nginx",
            ],
            "answer": "openssl s_client -connect site.example.com:443 -servername site.example.com",
            "points": 15,
            "root_cause": "The deployed leaf certificate has expired.",
            "remediation": [
                "Capture the live chain and dates",
                "Renew through the approved certificate process",
                "Deploy with rollback",
                "Reload and verify from clients",
            ],
            "unsafe_action": "Disabling TLS verification or opening the firewall does not renew the certificate.",
        },
        {
            "id": "INC-032",
            "level": "Intermediate",
            "category": "Transfer",
            "title": "File copy completes but destination differs",
            "brief": "A configuration transfer reports success, but checksum verification fails.",
            "symptoms": ["File sizes are close", "The transfer was resumed", "Source changes during copying"],
            "evidence": [
                "sha256 sums differ",
                "Source mtime changed during transfer",
                "rsync dry run lists one changed block",
            ],
            "question": "Which command performs a dry-run synchronisation check?",
            "options": [
                "rsync -avn source/ server:/opt/app/",
                "rm -rf server:/opt/app",
                "scp -r / server:/",
                "chmod 777 source",
            ],
            "answer": "rsync -avn source/ server:/opt/app/",
            "points": 15,
            "root_cause": "The source changed while the original transfer was running.",
            "remediation": [
                "Freeze or version the source",
                "Run rsync dry run",
                "Synchronise the approved version",
                "Verify checksums",
            ],
            "unsafe_action": "Copying the root filesystem or deleting the destination is disproportionate and dangerous.",
        },
        {
            "id": "INC-033",
            "level": "Intermediate",
            "category": "Security",
            "title": "SELinux denies web content access",
            "brief": "File permissions appear correct, but the web server receives permission denied.",
            "symptoms": ["Mode is 0644", "Owner is expected", "The system is enforcing SELinux"],
            "evidence": [
                "audit log records AVC denial",
                "ls -Z shows an unusual context",
                "A copied file retained a home-directory label",
            ],
            "question": "Which command previews restoration of the default context?",
            "options": [
                "restorecon -nRv /var/www/html",
                "setenforce 0 permanently",
                "chmod -R 777 /var/www",
                "rm -rf /etc/selinux",
            ],
            "answer": "restorecon -nRv /var/www/html",
            "points": 15,
            "root_cause": "The deployed files have incorrect SELinux contexts.",
            "remediation": [
                "Review the AVC record",
                "Preview restorecon changes",
                "Restore approved contexts",
                "Retest while enforcement remains enabled",
            ],
            "unsafe_action": "Disabling SELinux removes a security control and hides the actual labelling issue.",
        },
        {
            "id": "INC-034",
            "level": "Intermediate",
            "category": "Network",
            "title": "Network interface negotiates at low speed",
            "brief": "Large transfers are unexpectedly slow after a cable change.",
            "symptoms": ["CPU is low", "Packet loss is small", "Throughput is capped near 100 Mbps"],
            "evidence": [
                "ethtool reports 100Mb/s half duplex",
                "The switch expects 1Gb/s full duplex",
                "Error counters increase",
            ],
            "question": "Which command inspects link negotiation?",
            "options": ["ethtool eth0", "df -h", "journalctl --vacuum-size=10M", "kill -9 1"],
            "answer": "ethtool eth0",
            "points": 15,
            "root_cause": "The interface negotiated the wrong speed and duplex due to a cable or port problem.",
            "remediation": [
                "Record link settings and counters",
                "Check cable and switch port",
                "Restore auto-negotiation or approved settings",
                "Retest throughput",
            ],
            "unsafe_action": "Changing application timeouts does not repair a physical link mismatch.",
        },
        {
            "id": "INC-035",
            "level": "Intermediate",
            "category": "Users",
            "title": "Account remains locked after password reset",
            "brief": "A user has a new password but authentication is still rejected.",
            "symptoms": ["The password was changed", "The username exists", "Other users can log in"],
            "evidence": ["passwd -S reports locked", "Failed-attempt policy triggered a lock", "The shell is valid"],
            "question": "Which command checks password status?",
            "options": ["passwd -S analyst", "chmod 777 /etc/shadow", "rm /etc/passwd", "reboot"],
            "answer": "passwd -S analyst",
            "points": 15,
            "root_cause": "The account password remains locked after the reset.",
            "remediation": [
                "Inspect account status and policy",
                "Unlock through the approved process",
                "Confirm expiry and shell",
                "Test a new session",
            ],
            "unsafe_action": "Editing password databases manually can corrupt accounts and expose credentials.",
        },
        {
            "id": "INC-036",
            "level": "Intermediate",
            "category": "Logs",
            "title": "Rotated logs consume all disk space",
            "brief": "The active application log is small, but /var/log remains nearly full.",
            "symptoms": ["Log rotation runs nightly", "Many compressed files exist", "Retention recently changed"],
            "evidence": [
                "du identifies old .gz archives",
                "logrotate debug shows 90 rotations retained",
                "Policy intended only 14 days",
            ],
            "question": "Which command previews logrotate behaviour?",
            "options": [
                "logrotate -d /etc/logrotate.conf",
                "rm -rf /var/log",
                "chmod 777 /var/log",
                "systemctl restart every-service",
            ],
            "answer": "logrotate -d /etc/logrotate.conf",
            "points": 15,
            "root_cause": "An incorrect retention count keeps months of compressed logs.",
            "remediation": [
                "Run logrotate in debug mode",
                "Correct the policy",
                "Remove only approved expired archives",
                "Monitor retained size",
            ],
            "unsafe_action": "Deleting all logs destroys audit and diagnostic evidence.",
        },
        {
            "id": "INC-037",
            "level": "Intermediate",
            "category": "Containers",
            "title": "Container health check fails although process runs",
            "brief": "The application container is Up but marked unhealthy.",
            "symptoms": [
                "The main PID remains active",
                "Users see intermittent failures",
                "The image was recently changed",
            ],
            "evidence": [
                "docker inspect shows failing health command",
                "The command references removed curl binary",
                "Application endpoint works with wget",
            ],
            "question": "Which command shows the configured health check and state?",
            "options": [
                "docker inspect app-container",
                "docker rm -f app-container",
                "rm -rf /var/lib/docker",
                "ufw disable",
            ],
            "answer": "docker inspect app-container",
            "points": 15,
            "root_cause": "The image no longer contains the utility used by the health check.",
            "remediation": [
                "Inspect health configuration and output",
                "Choose a command available in the image",
                "Rebuild and test the image",
                "Deploy with rollback",
            ],
            "unsafe_action": "Removing the container without correcting the image only recreates the same failure.",
        },
        {
            "id": "INC-038",
            "level": "Advanced",
            "category": "Kernel",
            "title": "Application crashes with a core dump",
            "brief": "A native service exits with segmentation fault under a specific request.",
            "symptoms": [
                "The unit restarts automatically",
                "A core dump is recorded",
                "CPU and memory are otherwise normal",
            ],
            "evidence": [
                "coredumpctl lists the service PID",
                "Stack metadata identifies a shared-library call",
                "The issue is repeatable",
            ],
            "question": "Which command displays core-dump metadata?",
            "options": [
                "coredumpctl info service-name",
                "rm -rf /var/lib/systemd/coredump",
                "chmod 777 /usr/lib",
                "reboot",
            ],
            "answer": "coredumpctl info service-name",
            "points": 20,
            "root_cause": "A native-code defect triggers a segmentation fault in a shared-library call.",
            "remediation": [
                "Preserve the core and binary versions",
                "Inspect metadata and stack trace",
                "Reproduce safely",
                "Escalate with evidence and deploy a fixed build",
            ],
            "unsafe_action": "Deleting core dumps before analysis removes the strongest failure evidence.",
        },
        {
            "id": "INC-039",
            "level": "Advanced",
            "category": "Security",
            "title": "Repeated failed logins from one address",
            "brief": "Authentication logs show a burst of failed SSH attempts.",
            "symptoms": [
                "The service remains available",
                "No successful login is recorded",
                "One source dominates events",
            ],
            "evidence": [
                "ausearch correlates USER_AUTH failures",
                "Firewall counters show repeated attempts",
                "The account is privileged",
            ],
            "question": "Which command searches recent audit authentication events?",
            "options": [
                "ausearch -m USER_AUTH --start today",
                "chmod 777 /etc/ssh",
                "iptables -F",
                "rm /var/log/audit/audit.log",
            ],
            "answer": "ausearch -m USER_AUTH --start today",
            "points": 20,
            "root_cause": "An external source is repeatedly attempting authentication against a privileged account.",
            "remediation": [
                "Preserve audit records",
                "Confirm no successful access",
                "Apply approved rate limiting or source controls",
                "Review account and key policy",
            ],
            "unsafe_action": "Deleting logs or flushing firewall rules weakens both evidence and protection.",
        },
        {
            "id": "INC-040",
            "level": "Advanced",
            "category": "Performance",
            "title": "Virtual machine shows unexplained latency",
            "brief": "CPU usage inside the guest is moderate, but response time spikes.",
            "symptoms": ["Load increases during host contention", "I/O wait is low", "The VM shares a busy hypervisor"],
            "evidence": [
                "mpstat shows high steal time",
                "Guest processes do not consume the missing CPU",
                "Other VMs report similar timing",
            ],
            "question": "Which command shows per-CPU steal time?",
            "options": ["mpstat -P ALL 1 5", "df -i", "dig example.com", "mount -a"],
            "answer": "mpstat -P ALL 1 5",
            "points": 20,
            "root_cause": "Hypervisor contention is taking CPU time away from the guest.",
            "remediation": [
                "Collect repeated steal-time samples",
                "Correlate with host metrics",
                "Move or resize the workload",
                "Verify latency after remediation",
            ],
            "unsafe_action": "Tuning guest processes cannot recover CPU time withheld by the hypervisor.",
        },
        {
            "id": "INC-041",
            "level": "Advanced",
            "category": "Network",
            "title": "TLS requests fail only for one hostname",
            "brief": "The server hosts several HTTPS sites, but one hostname returns the wrong certificate.",
            "symptoms": ["Port 443 is reachable", "Other names work", "The certificate belongs to a default site"],
            "evidence": [
                "openssl without SNI shows the default certificate",
                "With SNI the wrong virtual host still answers",
                "Server-name mapping is incorrect",
            ],
            "question": "Which command tests the endpoint with explicit SNI?",
            "options": [
                "openssl s_client -connect 203.0.113.10:443 -servername api.example.com",
                "ping -c 4 api.example.com",
                "df -h",
                "docker system prune",
            ],
            "answer": "openssl s_client -connect 203.0.113.10:443 -servername api.example.com",
            "points": 20,
            "root_cause": "The TLS virtual-host configuration maps api.example.com to the wrong certificate.",
            "remediation": [
                "Capture SNI-aware output",
                "Inspect virtual-host order and names",
                "Correct certificate mapping",
                "Reload and test all hosted names",
            ],
            "unsafe_action": "Replacing every certificate or disabling verification broadens impact without fixing mapping.",
        },
        {
            "id": "INC-042",
            "level": "Advanced",
            "category": "Network",
            "title": "Large packets fail across VPN",
            "brief": "Small requests work, but file uploads stall over a tunnel.",
            "symptoms": [
                "Ping with default size succeeds",
                "Large TLS records retransmit",
                "The VPN adds encapsulation overhead",
            ],
            "evidence": [
                "tracepath reports lower path MTU",
                "Do-not-fragment probes fail above 1360 bytes",
                "Interface MTU remains 1500",
            ],
            "question": "Which command estimates path MTU?",
            "options": [
                "tracepath vpn.example.com",
                "rm /etc/resolv.conf",
                "chmod 777 /dev/net/tun",
                "killall openvpn",
            ],
            "answer": "tracepath vpn.example.com",
            "points": 20,
            "root_cause": "The tunnel path MTU is lower than the interface MTU, causing fragmentation or black-holing.",
            "remediation": [
                "Measure path MTU",
                "Confirm tunnel overhead",
                "Apply approved MSS or MTU correction",
                "Retest large transfers",
            ],
            "unsafe_action": "Increasing application timeouts only prolongs failures caused by packet size.",
        },
        {
            "id": "INC-043",
            "level": "Advanced",
            "category": "Firewall",
            "title": "Connection tracking table is exhausted",
            "brief": "New connections fail while existing sessions continue.",
            "symptoms": ["CPU is moderate", "Listening services are healthy", "Failure affects many ports"],
            "evidence": [
                "Kernel logs report nf_conntrack table full",
                "Connection count is unusually high",
                "A client retry storm is active",
            ],
            "question": "Which command inspects current socket totals first?",
            "options": ["ss -s", "iptables -F", "reboot", "rm /proc/sys/net/netfilter/nf_conntrack_max"],
            "answer": "ss -s",
            "points": 20,
            "root_cause": "A retry storm exhausts connection-tracking capacity.",
            "remediation": [
                "Quantify socket states",
                "Identify retry sources",
                "Reduce the storm",
                "Review conntrack sizing only after traffic correction",
            ],
            "unsafe_action": "Flushing all firewall rules removes protection and does not stop the retry source.",
        },
        {
            "id": "INC-044",
            "level": "Advanced",
            "category": "Storage",
            "title": "Disk latency rises without high throughput",
            "brief": "Database requests stall although MB/s remains modest.",
            "symptoms": ["CPU is idle", "Queue depth increases", "The storage volume is shared"],
            "evidence": ["iostat shows high await", "%util remains near 100%", "Small random writes dominate"],
            "question": "Which command samples extended device latency metrics?",
            "options": ["iostat -xz 1 5", "uname -a", "host database", "chmod 777 /var/lib/db"],
            "answer": "iostat -xz 1 5",
            "points": 20,
            "root_cause": "The shared device is saturated by high-latency random I/O rather than throughput volume.",
            "remediation": [
                "Capture several samples",
                "Identify the process and I/O pattern",
                "Reduce contention or move storage",
                "Verify latency and application recovery",
            ],
            "unsafe_action": "Adding CPU or changing file permissions cannot resolve device queue latency.",
        },
        {
            "id": "INC-045",
            "level": "Advanced",
            "category": "Resources",
            "title": "Service cannot open more files",
            "brief": "A proxy begins rejecting connections with too many open files.",
            "symptoms": ["Process remains active", "Connection volume increased", "Disk and memory are normal"],
            "evidence": [
                "journal records EMFILE",
                "prlimit shows a low nofile soft limit",
                "ss shows many established sockets",
            ],
            "question": "Which command inspects the running process limits?",
            "options": [
                "prlimit --pid 2101",
                "rm -rf /proc/2101/fd",
                "ulimit -n 999999 in an unrelated shell",
                "reboot",
            ],
            "answer": "prlimit --pid 2101",
            "points": 20,
            "root_cause": "The proxy process has reached its configured open-file soft limit.",
            "remediation": [
                "Inspect process limits and descriptor use",
                "Find leaks or expected capacity needs",
                "Update the service limit safely",
                "Restart during an approved window and verify",
            ],
            "unsafe_action": "Deleting descriptors through proc or changing an unrelated shell limit is unsafe and ineffective.",
        },
        {
            "id": "INC-046",
            "level": "Advanced",
            "category": "Boot",
            "title": "Server boot is delayed by several minutes",
            "brief": "The machine eventually starts, but services wait during every boot.",
            "symptoms": ["The delay is repeatable", "Storage is healthy", "A network mount is optional"],
            "evidence": [
                "systemd-analyze blame ranks a mount wait first",
                "critical-chain includes network-online",
                "The remote share is unavailable",
            ],
            "question": "Which command reveals the critical boot dependency path?",
            "options": ["systemd-analyze critical-chain", "rm /etc/fstab", "chmod 777 /etc/systemd", "kill -9 1"],
            "answer": "systemd-analyze critical-chain",
            "points": 20,
            "root_cause": "An optional remote mount blocks the boot dependency chain while waiting for the network.",
            "remediation": [
                "Capture blame and critical chain",
                "Review mount requirements and timeout options",
                "Make the dependency non-blocking if approved",
                "Test multiple boots",
            ],
            "unsafe_action": "Deleting fstab can prevent required filesystems from mounting and create a larger outage.",
        },
        {
            "id": "INC-047",
            "level": "Advanced",
            "category": "Containers",
            "title": "Container uses increasing memory until restart",
            "brief": "A service container is stable for hours, then is killed and recreated.",
            "symptoms": ["Memory rises monotonically", "CPU remains normal", "The restart policy masks the failure"],
            "evidence": ["docker stats shows growth", "Kernel logs record an OOM kill", "Container limit is reached"],
            "question": "Which command captures one container resource snapshot?",
            "options": [
                "docker stats --no-stream app-container",
                "docker rm -f app-container",
                "rm -rf /var/lib/docker",
                "ufw disable",
            ],
            "answer": "docker stats --no-stream app-container",
            "points": 20,
            "root_cause": "The application leaks memory until it reaches the container limit and is OOM-killed.",
            "remediation": [
                "Collect repeated resource samples",
                "Confirm OOM evidence",
                "Capture application diagnostics",
                "Fix the leak and retain a protective limit",
            ],
            "unsafe_action": "Removing or repeatedly restarting the container hides the leak and discards evidence.",
        },
        {
            "id": "INC-048",
            "level": "Advanced",
            "category": "Security",
            "title": "Kernel module required by networking is absent",
            "brief": "A container platform reports that bridge filtering support is unavailable.",
            "symptoms": [
                "The configuration file exists",
                "The kernel was recently updated",
                "Networking partially works",
            ],
            "evidence": [
                "lsmod lacks br_netfilter",
                "modinfo finds the module",
                "sysctl keys are absent until loading",
            ],
            "question": "Which command previews module loading actions?",
            "options": [
                "modprobe --dry-run -v br_netfilter",
                "rm -rf /lib/modules",
                "sysctl -w every.key=1",
                "reboot repeatedly",
            ],
            "answer": "modprobe --dry-run -v br_netfilter",
            "points": 20,
            "root_cause": "The required module was not loaded after the kernel update.",
            "remediation": [
                "Verify module availability",
                "Preview dependency loading",
                "Load through approved configuration",
                "Set required parameters and test",
            ],
            "unsafe_action": "Deleting module files or writing unrelated kernel keys can make the host unbootable or unstable.",
        },
        {
            "id": "INC-049",
            "level": "Advanced",
            "category": "Performance",
            "title": "System call failures occur only under load",
            "brief": "A service returns intermittent resource unavailable errors at peak traffic.",
            "symptoms": [
                "Application logs lack detail",
                "CPU is below saturation",
                "The error happens during file creation",
            ],
            "evidence": [
                "strace shows EMFILE from openat",
                "Open descriptors approach the process limit",
                "Requests recover after restart",
            ],
            "question": "Which command traces file-related system calls for the PID?",
            "options": ["strace -f -e trace=file -p 2142", "df -h", "dig example.com", "iptables -F"],
            "answer": "strace -f -e trace=file -p 2142",
            "points": 20,
            "root_cause": "A file-descriptor leak causes openat calls to fail at the process limit.",
            "remediation": [
                "Attach a focused trace briefly",
                "Confirm descriptor growth with lsof",
                "Fix the leak",
                "Set a justified limit and monitor",
            ],
            "unsafe_action": "Running an unrestricted trace for long periods can create heavy overhead and expose sensitive arguments.",
        },
        {
            "id": "INC-050",
            "level": "Advanced",
            "category": "Firewall",
            "title": "A new nftables policy blocks return traffic",
            "brief": "Outbound connections start but never complete after a ruleset deployment.",
            "symptoms": ["DNS queries leave the host", "Replies arrive at the interface", "Applications time out"],
            "evidence": [
                "tcpdump sees reply packets",
                "nft counters show drops in input chain",
                "Established-state accept rule is missing",
            ],
            "question": "Which command lists the active nftables ruleset?",
            "options": ["nft list ruleset", "iptables -F", "rm /etc/nftables.conf", "chmod 777 /etc"],
            "answer": "nft list ruleset",
            "points": 20,
            "root_cause": "The new policy omits an established and related state rule, so return traffic is dropped.",
            "remediation": [
                "Preserve the active ruleset",
                "Inspect counters and state handling",
                "Apply a validated correction with rollback",
                "Test new and established flows",
            ],
            "unsafe_action": "Flushing all rules can expose the host and removes evidence of the faulty rule path.",
        },
    ]
)


def incidents_for_level(level: str) -> list[Incident]:
    return [item for item in INCIDENTS if item["level"] == level]
